apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: 
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
  - image: dtriana/nginx
    context: servers/nginx
  - image: dtriana/es3
    context: servers/elastic-s3
    docker:
      buildArgs:
        ACCESS_KEY: "YOUR_ACCESS_KEY"
        SECRET_KEY: "YOUR_SECRET_KEY"
        ENDPOINT: "EP_GOES_HERE"
 
deploy:
  kubectl:
    manifests:
      - ./kubernetes/service-account.yaml
      - ./kubernetes/es-svc.yaml
      - ./kubernetes/es-rc.yaml
      - ./kubernetes/rbac.yaml
#      - ./kubernetes/nginx.yaml
