apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: revproxy
spec:
  type: NodePort
  selector:
    app: revproxy
  ports:
  - name: http
    port: 9200
    nodePort: 30920
    protocol: TCP
  - name: transport
    port: 9300
    nodePort: 30930
    protocol: TCP

