apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: revproxy
spec:
  type: LoadBalancer
  selector:
    app: revproxy
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP

